name: Android CI

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    env:
      ANDROID_API: 29
      ANDROID_BUILD_TOOLS_VERSION: 34.0.0
      ANDROID_NDK_VERSION: 26.3.11579264
      ANDROID_SDK_PACKAGES: 'tools platform-tools platform;android-${{ env.ANDROID_API }} build-tools;${{ env.ANDROID_BUILD_TOOLS_VERSION }} ndk;${{ env.ANDROID_NDK_VERSION }}'
      JDK_VERSION: 17
      API: ${{ env.ANDROID_API }}
      ANDROID_SDK_ROOT: ${{ github.WORKSPACE }}/.android/sdk
      ANDROID_NDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}/ndk/${{ env.ANDROID_NDK_VERSION }}
      BUILDBASEDIR: ${{ github.WORKSPACE }}/packaging/android
      PREFIXDIR: ${{ env.BUILDBASEDIR }}/prefix
      DOWNLOADDIR: ${{ env.BUILDBASEDIR }}/download
      BUILDDIR: ${{ env.BUILDBASEDIR }}/build
      AABBASEDIR: ${{ env.BUILDBASEDIR }}/aab-base
      APKBASEDIR: ${{ env.BUILDBASEDIR }}
      AABOUTPUT: ${{ env.BUILDBASEDIR }}/wesnoth-debug.aab
      APKSOUTPUT: ${{ env.BUILDBASEDIR }}/wesnoth-debug.apks
      APKOUTPUT: ${{ env.BUILDBASEDIR }}/wesnoth-debug.apk

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1

      - name: Fetch submodules
        run: git submodule update --init --recursive; ls -lh;

      - name: Install auxiliary build tools
        run: sudo apt-get install -y meson gperf scons

      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '${{ JDK_VERSION }}'
          distribution: 'temurin'

      - name: Cache Android SDK
        id: cache-android-sdk
        uses: actions/cache@v3
        with:
          key: android-sdk ${{ env.ANDROOD_SDK_PACKAGES }}
          path: ${{ env.ANDROID_SDK_ROOT }}

      - if ${{ steps.cache-android-sdk.cache-hit  != 'true' }}
        name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ${{ env.ANDROID_SDK_PACKAGES }}

      - name: Cache Wesnoth dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          key: wesnoth-android-deps-r1
          path: ${{ env.PREFIXDIR }}

      - name: Download and build Wesnoth dependencies
        run: cd packaging/android/build-android-dependencies; ./build-android-deps.sh;

      - name: Build Wesnoth and create APKS
        run: ls -lh; cd packaging/android; PATH=$PATH:$ANDROID_SDK_ROOT/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }} ./build-apks;

      - name: Upload APKS
        uses: actions/upload-artifact@v4.3.1
        with:
          name: wesnoth-debug.apks
          path: ${{ env.APKSOUTPUT }}
            
            #- name: Grant execute permission for gradlew
            #  run: chmod +x gradlew
            #- name: Build with Gradle
            #  run: ./gradlew build
            
